repos:

- repo: https://github.com/yelp/detect-secrets.git
  rev: v0.13.1
  hooks:
  -   id: detect-secrets
      name: Detect Secrets (Yelp)
      args: ['--baseline', '.secrets.baseline']
      exclude: .*/go.sum

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
