repos:

- repo: https://github.com/yelp/detect-secrets.git
  rev: v1.1.0
  hooks:
  -   id: detect-secrets
      name: detect secrets
      args: ['--baseline', '.secrets.baseline']

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: trailing-whitespace
      name: trailing whitespace
    - id: end-of-file-fixer
      name: end of file fixer
    - id: check-added-large-files
      name: check added large files
